jugadores:
textures:
    conseguido:
        material: EMERALD_BLOCK
        customModelData: -1
    noConseguido:
        material: REDSTONE_BLOCK
        customModelData: -1
    conseguible:
        material: GOLD_BLOCK
        customModelData: -1
    noConseguible:
        material: REDSTONE_BLOCK
        customModelData: -1
levels:
    2:
        requirements:
            money: 
                umlcoins: 100
                ecoins:
            xp: 2
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    3:
        requirements:
            money:
                umlcoins:
                ecoins: 300
            xp: 20
            items:
        prices:
            money:
                umlcoins: 30
                ecoins: 2000
            xp: 30
            items:
            permissions:
                code:
                description:
    4:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    5:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    6:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    7:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    8:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    9:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    10:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    11:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    12:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    13:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    14:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    15:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    16:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    17:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    18:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    19:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    20:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    21:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    22:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    23:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    24:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    25:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    26:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    27:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    28:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    29:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    30:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    31:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    32:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    33:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    34:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    35:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    36:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    37:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    38:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    39:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    40:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    41:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    42:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    43:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    44:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    45:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    46:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    47:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    48:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    49:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    50:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    51:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    52:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    53:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    54:
        requirements:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
        prices:
            money:
                umlcoins:
                ecoins:
            xp:
            items:
            permissions:
                code:
                description:
    
    